version: '3.9'

services:
  web:
    build: .
    command: >	    
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      # монтирует текущую директорию (.) на локальной машине в директорию /code внутри контейнера.
      - .:/app
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on: # сервис web запускается только после db
      db:
        condition: service_healthy


  db:
    image: postgres:16.0 # образ
    env_file: # переменные окружения
      - .env
    expose:
      - "5432"
    volumes: # том `postgres_data` для хранения данных базы данных
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s # интервал между проверками
      timeout: 10s # время ожидания команды
      retries: 5 # количество попыток

networks:
  default:

volumes:
  postgres_data:
  static_volume:
