name: Django CI

on: [push, pull_request] # события, которые происходят

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      HOST: ${{ secrets.HOST }}
      NAME_DB: ${{ secrets.NAME_DB }}
      PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
      PORT: ${{ secrets.PORT }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TELEGRAM_URL: ${{ secrets.TELEGRAM_URL }}
      USER: ${{ secrets.USER }}
      DEBUG: ${{ secrets.DEBUG }}


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python # установка python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install poetry # установка poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies # установка зависимостей
        run: poetry install --no-interaction

      - name: Run migrate # запуск миграций
        run: poetry run python manage.py migrate

      - name: Run tests # запуск тестирования
        run: poetry run python test.py
