name: Django CI

on: [push, pull_request] # события, которые происходят

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env: # переменные окружения и секреты
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      HOST: ${{ secrets.HOST }}
      NAME_DB: ${{ secrets.NAME_DB }}
      PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
      PORT: ${{ secrets.PORT }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TELEGRAM_URL: ${{ secrets.TELEGRAM_URL }}
      USER: ${{ secrets.USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{secrets.SSH_USER}}
      DEBUG: ${{ secrets.DEBUG }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN : ${{ secrets.DOCKER_HUB_ACCESS_TOKEN  }}

    services:
      postgres: # PostgreSQL
        image: postgres:14
        env:
          POSTGRES_DB: ${{ secrets.NAME_DB }}
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

      redis: # Redis
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python # установка python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install poetry # установка poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies # установка зависимостей
        run: poetry install --no-interaction --no-root

      - name: Run migrate # запуск миграций
        run: poetry run python manage.py migrate

      - name: Run tests # запуск тестирования
        run: poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in in Docker hub # аутентификация в Docker hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image # сборка образа
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image in Docker hub # загрузка образа
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH # настройка SSH-подключения
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server # Деплой на сервер
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker stop myapp || true
            docker rm myapp || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
            docker run -d --name myapp -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
          EOF